# Generated by Django 5.2 on 2025-05-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_userprofile_contactnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilepic',
            new_name='profile_pic',
        ),
    ]
