# Generated by Django 5.2 on 2025-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_userprofile_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
