# Generated by Django 5.2 on 2025-05-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_remove_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contactnumber',
            new_name='contact_number',
        ),
    ]
